### ISSUE TITLE
CMakeLists.txt should not explicitly list source files explicitly

### ISSUE THREAD

**Issue by jayjaybillings** [dgquvn/repo#13]
The CMakeLists.txt file at https://github.com/dgquvn/repo/blob/master/FizzBuzz_generic_v2/FizzBuzz_classes/CMakeLists.txt lists the source files explicitly:
```cmake
set(FizzBuzz_classes_SRCS
   Controller.cpp
   inputProperties.cpp
   variables.cpp
   OutputGenerator.cpp
   FileWriter.cpp
)
```
However, this is not good because adding a file or changing the name of an existing file requires manually updating the build system. It should be updated to use CMake's GLOB construct:
```cmake
#Collect all header filenames in this project 
#and glob them in HEADERS
file(GLOB HEADERS *.h)

#Grab all of the source files
file(GLOB SRC *.cpp)
```

**Comment by dgquvn** [comment]
done
