### ISSUE TITLE
FizzBuzz code need thorough Doxygen documentation

### ISSUE THREAD

**Issue by jayjaybillings** [dgquvn/repo#14]
The project is largely missing API-level documentation and should be updated to use Doxygen. Here is a good resource for that: http://csweb.cs.wfu.edu/~fulp/CSC112/codeStyle.html

Also there are good examples in Fire: https://github.com/jayjaybillings/fire/blob/master/astrophysics/Species.h

**Comment by dgquvn** [comment]
I tried to add Doxygen documentation.  It seems it's not working.  Let me know where I set incorrect.

**Comment by dgquvn** [comment]
Never mind, I think I think it is actually working.  I just need to add more comments

**Comment by jayjaybillings** [comment]
I noticed in main() that you put the documentation before the function declaration. It should go above for it to be scanned by Doxygen and filled correctly.

Congrats on figuring this out though! Doxygen can be tough.

Jay Jay Billings
Team Lead, Scientific Software Development
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by dgquvn** [comment]
I think I have corrected that and made it work, although there might be some warning msg I haven't paid attention to.  And I also include the simple OpenMP parrallel for loop

**Comment by dgquvn** [comment]
I think this should be ok for this ticket and I'll remove the omp_set_num_threads for openmp
