### ISSUE TITLE
HOWTO execute FizzBuzz?

### ISSUE THREAD

**Issue by jayjaybillings** [dgquvn/repo#15]
How do I execute this code? When I do
```bash
mkdir build
cd build
cmake ..
make
make test
./FizzBuzz_v2
```
I get
```bash
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```

What files and arguments to I need to run the code? It would be best to put this information in the README.md file.

**Comment by dgquvn** [comment]
Right now I can only do this 
./FizzBuzz_v2 input.txt output.txt
if the data files are in the build directory, Otherwise, they need to be specified the whole directory. I am adding boost/program_options soon.

**Comment by dgquvn** [comment]
boost/program_options added and added README.md

**Comment by dgquvn** [comment]
I think this should be closed now
