### ISSUE TITLE
main() (or something) should check arguments

### ISSUE THREAD

**Issue by jayjaybillings** [dgquvn/repo#16]
main() or some other function should check the input arguments before attempting to use them. For example, running FizzBuzz_v2 with no arguments produces
```bash
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```
but it should produce an easy to understand error message with instructions. For reference, see the information and example here: http://www.cplusplus.com/articles/DEN36Up4/

**Comment by dgquvn** [comment]
added boost/program_options and handling the errors

**Comment by jayjaybillings** [comment]
I didn't see it yet, but that could be my Android client.

**Comment by dgquvn** [comment]
There was some kind of error not updating at first.  But it's there

**Comment by dgquvn** [comment]
This should also be closed now.  Let me know if there is any need suggestions

**Comment by jayjaybillings** [comment]
It is customary to process options in a separate function completely. Your goal should be for main() to only call other functions and therefore be as short as possible. (Maybe only a single branch or loop.)
