### ISSUE TITLE
src and test directories

### ISSUE THREAD

**Issue by jayjaybillings** [dgquvn/repo#7]
You should put your source code files in a src directory and create a tests directory where you will put your tests. Note that Git will not commit an empty directory, so you may just need to put a dummy file in there for now.

**Comment by dgquvn** [comment]
Should I put my main source code and library files all in src directory? I'll have to update my CMakeLists.txt

**Comment by jayjaybillings** [comment]
Yes.

Jay Jay Billings
Team Lead, Scientific Software Development
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by dgquvn** [comment]
done
