### ISSUE TITLE
Where's the test you wanted me to look at?

### ISSUE THREAD

**Issue by jayjaybillings** [dgquvn/repo#9]
@dgquvn Where's the test you wanted me to look at? I checked out the code this morning and built the version in the FizzBuzz repo, but couldn't find a tests/ directory. Just let me know and I'll give it a look.

**Comment by dgquvn** [comment]
Hello Jay,

tests/directory is within the FizzBuzz_classes.  The test “test_inputProperties.cpp” has two tests, where the commented first test is the one which I want you to find out why it failed to test.

Best regards,
Blueze

**Comment by jayjaybillings** [comment]
Are you sure that you committed and pushed it? I don't see it in the repo.

**Comment by dgquvn** [comment]
Yes, I did.  It is in the directory below

repo/FizzBuzz_generic_v2/FizzBuzz_classes/tests/test_inputProperties.cpp

**Comment by jayjaybillings** [comment]
I see it in the master branch but not the FizzBuzz branch. I'll look into it.

**Comment by jayjaybillings** [comment]
I fixed the test in PR #11 and commit a14bec0.

The problem that I encountered when I tried to compile was that BOOST_CHECK_EQUAL cannot directly compare two maps. The solution that I provided in my PR is one good, succinct way to check the maps.

**Comment by jayjaybillings** [comment]
Since you accepted the pull request, I'm going to close this.
